/****** TOW WITH VEHICLE  ******/

/**
 * List of class names of vehicles which can tow towables objects.
 */
R3F_LOG_CFG_remorqueurs =
[
	"SUV_01_base_F",
	"Offroad_01_base_F",
	"Offroad_02_base_F",
	"Van_01_base_F",
	"Van_02_base_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"Boat_Armed_01_base_F",
	//Cup vehicles
	"CUP_C_Skoda_Blue_CIV",
	"CUP_C_Datsun_Covered",
	"CUP_C_Datsun_Plain",
	"CUP_C_Datsun_Tubeframe",
	"CUP_C_Golf4_red_Civ", 
	"CUP_C_Ikarus_Chernarus",
	"CUP_I_BTR40_TKG", 
	"CUP_B_HMMWV_Transport_NATO_T",
	"CUP_B_HMMWV_Terminal_NATO_T",
	"CUP_B_HMMWV_Unarmed_NATO_T",
	"CUP_B_HMMWV_Ambulance_ACR",
	"CUP_O_GAZ_Vodnik_MedEvac_RU",
	"CUP_B_LR_Ambulance_CZ_D",
	"CUP_B_LR_Ambulance_CZ_W",
	"CUP_B_LR_Transport_CZ_D",
	"CUP_B_LR_Transport_CZ_W",
	//"CUP_B_M1030_USMC",
	"CUP_B_M1133_MEV_Woodland",
	"CUP_B_M1133_MEV_Woodland_Slat",
	"CUP_B_M113_Med_USA",
	"CUP_B_MTVR_Ammo_USA",
	"CUP_B_MTVR_Refuel_USA",
	"CUP_B_MTVR_Repair_USA",
	"CUP_B_MTVR_USA",
	"CUP_B_T810_Reammo_CZ_WDL",
	"CUP_B_T810_Unarmed_CZ_WDL",
	"CUP_B_T810_Refuel_CZ_WDL",
	"CUP_B_T810_Repair_CZ_WDL",
	"CUP_B_TowingTractor_USMC",
	"CUP_I_SUV_ION",
	"CUP_B_UAZ_Open_ACR",
	"CUP_B_UAZ_Unarmed_ACR",
	"CUP_B_Ural_Reammo_CDF",
	"CUP_B_Ural_Empty_CDF",
	"CUP_B_Ural_Refuel_CDF",
	"CUP_B_Ural_Repair_CDF",
	"CUP_B_Ural_Open_CDF",
	"CUP_B_Ural_CDF",
	//Cup Veichles Armored
	"CUP_I_BTR40_MG_TKG",
	"CUP_I_BTR60_UN",
	"CUP_B_BRDM2_HQ_CZ",
	"CUP_B_BRDM2_CZ",
	"CUP_B_BAF_Coyote_GMG_W",
	"CUP_I_Datsun_PK",
	"CUP_B_Dingo_GL_CZ_Wdl",
	"CUP_B_Dingo_CZ_Wdl",
	"CUP_O_GAZ_Vodnik_PK_RU",
	"CUP_O_GAZ_Vodnik_AGS_RU",
	"CUP_O_GAZ_Vodnik_BPPU_RU",
	"CUP_B_HMMWV_Avenger_NATO_T",
	"CUP_B_HMMWV_Crows_M2_NATO_T",
	"CUP_B_HMMWV_Crows_MK19_NATO_T",
	"CUP_B_HMMWV_M2_GPK_NATO_T",
	"CUP_B_HMMWV_M2_NATO_T",
	"CUP_B_HMMWV_M1114_USMC",
	"CUP_B_HMMWV_MK19_NATO_T",
	"CUP_B_HMMWV_SOV_M2_NATO_T",
	"CUP_B_HMMWV_SOV_NATO_T",
	"CUP_B_HMMWV_TOW_NATO_T",
	"CUP_B_Jackal2_GMG_GB_W",
	"CUP_B_BAF_Coyote_L2A1_W",
	"CUP_B_Jackal2_L2A1_GB_W",
	"CUP_B_LR_MG_CZ_W",
	"CUP_B_LR_Special_CZ_W",
	"CUP_B_LAV25_USMC",
	"CUP_B_LAV25_HQ_USMC",
	"CUP_B_M1126_ICV_M2_Woodland_Slat",
	"CUP_B_M1126_ICV_M2_Woodland",
	"CUP_B_M1126_ICV_MK19_Woodland_Slat",
	"CUP_B_M1126_ICV_MK19_Woodland",
	"CUP_B_M1128_MGS_Woodland",
	"CUP_B_M1128_MGS_Woodland_Slat",
	"CUP_B_M1129_MC_MK19_Woodland_Slat",
	"CUP_B_M1129_MC_MK19_Woodland",
	"CUP_B_M1130_CV_M2_Woodland_Slat",
	"CUP_B_M1130_CV_M2_Woodland",
	"CUP_B_M1135_ATGMV_Woodland_Slat",
	"CUP_B_M1135_ATGMV_Woodland",
	"CUP_B_Mastiff_GMG_GB_W",
	"CUP_B_Mastiff_HMG_GB_W",
	"CUP_B_Mastiff_LMG_GB_W",
	"CUP_B_RG31_M2_GC_USMC",
	"CUP_B_RG31_M2_OD_USMC",
	"CUP_B_RG31_M2_USMC",
	"CUP_B_RG31_Mk19_OD_USMC",
	"CUP_B_RG31E_M2_USMC",
	"CUP_B_Ridgback_GMG_GB_W",
	"CUP_B_Ridgback_HMG_GB_W",
	"CUP_B_Ridgback_LMG_GB_W",
	"CUP_I_SUV_Armored_ION",
	"CUP_B_UAZ_AGS30_ACR",
	"CUP_B_UAZ_MG_ACR",
	"CUP_B_UAZ_METIS_ACR",
	"CUP_B_UAZ_SPG9_ACR",
	"CUP_B_Wolfhound_GMG_GB_W",
	"CUP_B_Wolfhound_HMG_GB_W",
	"CUP_B_Wolfhound_LMG_GB_W"
	// Cup Vehicles Tanks
	/*"CUP_O_2S6_RU",
	"CUP_B_AAV_USMC",
	"CUP_B_BMP_HQ_CDF",
	"CUP_B_BMP2_CDF",
	"CUP_B_Challenger2_Green_CTRG",
	"CUP_B_FV432_Bulldog_GB_W_RWS",
	"CUP_B_FV432_Bulldog_GB_W",
	"CUP_B_FV510_GB_W_SLAT",
	"CUP_B_FV510_GB_W",
	"CUP_B_M113_USA",
	"CUP_B_M163_USA",
	"CUP_B_M1A1_NATO_T",
	"CUP_B_M1A2_TUSK_MG_USMC",
	"CUP_B_M270_DPICM_USMC",
	"CUP_B_M270_HE_USMC",
	"CUP_B_M2Bradley_USA_W",
	"CUP_B_M2A3Bradley_USA_W",
	"CUP_B_M6LineBacker_USA_W",
	"CUP_B_M7Bradley_USA_D",
	"CUP_B_MCV80_GB_W_SLAT",
	"CUP_B_MCV80_GB_W",
	"CUP_I_T34_TK_GUE",
	"CUP_O_T55_CSAT",
	"CUP_B_T72_CDF",
	"CUP_B_T72_CZ",
	"CUP_O_T90_RU",
	"CUP_B_ZSU23_CDF",
	"CUP_B_Zodiac_USMC",
	"CUP_B_RHIB_USMC",
	"CUP_B_RHIB2Turret_USMC",
	"CUP_B_Seafox_USV_USMC"*/
];

/**
 * List of class names of HEAVY vehicles which can tow heavy towables objects. Takes precedence over R3F_LOG_CFG_remorqueurs
 */
R3F_LOG_CFG_remorqueursH =
[
	// Cup Vehicles Tanks
	"CUP_O_2S6_RU",
	"CUP_B_AAV_USMC",
	"CUP_B_BMP_HQ_CDF",
	"CUP_B_BMP2_CDF",
	"CUP_B_Challenger2_Green_CTRG",
	"CUP_B_FV432_Bulldog_GB_W_RWS",
	"CUP_B_FV432_Bulldog_GB_W",
	"CUP_B_FV510_GB_W_SLAT",
	"CUP_B_FV510_GB_W",
	"CUP_B_M113_USA",
	"CUP_B_M163_USA",
	"CUP_B_M1A1_NATO_T",
	"CUP_B_M1A2_TUSK_MG_USMC",
	"CUP_B_M270_DPICM_USMC",
	"CUP_B_M270_HE_USMC",
	"CUP_B_M2Bradley_USA_W",
	"CUP_B_M2A3Bradley_USA_W",
	"CUP_B_M6LineBacker_USA_W",
	"CUP_B_M7Bradley_USA_D",
	"CUP_B_MCV80_GB_W_SLAT",
	"CUP_B_MCV80_GB_W",
	"CUP_I_T34_TK_GUE",
	"CUP_O_T55_CSAT",
	"CUP_B_T72_CDF",
	"CUP_B_T72_CZ",
	"CUP_O_T90_RU",
	"CUP_B_ZSU23_CDF",
	"CUP_B_Zodiac_USMC",
	"CUP_B_RHIB_USMC",
	"CUP_B_RHIB2Turret_USMC",
	"CUP_B_Seafox_USV_USMC",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Truck_03_base_F",
	"Wheeled_APC_F",
	"Tank_F"
];

R3F_LOG_CFG_remorqueurs append R3F_LOG_CFG_remorqueursH;

/**
 * List of class names of towables objects.
 */
R3F_LOG_CFG_objets_remorquables =
[
	"Car_F",
	"Ship_F",
	"Plane",
	"UAV_03_base_F",
	"Heli_Light_01_base_F",
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"Heli_Attack_01_base_F",
	"CUP_C_Skoda_Blue_CIV",
	"CUP_C_Datsun_Covered",
	"CUP_C_Datsun_Plain",
	"CUP_C_Datsun_Tubeframe",
	"CUP_C_Golf4_red_Civ", 
	"CUP_C_Ikarus_Chernarus",
	"CUP_I_BTR40_TKG", 
	"CUP_B_HMMWV_Transport_NATO_T",
	"CUP_B_HMMWV_Terminal_NATO_T",
	"CUP_B_HMMWV_Unarmed_NATO_T",
	"CUP_B_HMMWV_Ambulance_ACR",
	"CUP_O_GAZ_Vodnik_MedEvac_RU",
	"CUP_B_LR_Ambulance_CZ_D",
	"CUP_B_LR_Ambulance_CZ_W",
	"CUP_B_LR_Transport_CZ_D",
	"CUP_B_LR_Transport_CZ_W",
	//"CUP_B_M1030_USMC",
	"CUP_B_M1133_MEV_Woodland",
	"CUP_B_M1133_MEV_Woodland_Slat",
	"CUP_B_M113_Med_USA",
	"CUP_B_MTVR_Ammo_USA",
	"CUP_B_MTVR_Refuel_USA",
	"CUP_B_MTVR_Repair_USA",
	"CUP_B_MTVR_USA",
	"CUP_B_T810_Reammo_CZ_WDL",
	"CUP_B_T810_Unarmed_CZ_WDL",
	"CUP_B_T810_Refuel_CZ_WDL",
	"CUP_B_T810_Repair_CZ_WDL",
	"CUP_B_TowingTractor_USMC",
	"CUP_I_SUV_ION",
	"CUP_B_UAZ_Open_ACR",
	"CUP_B_UAZ_Unarmed_ACR",
	"CUP_B_Ural_Reammo_CDF",
	"CUP_B_Ural_Empty_CDF",
	"CUP_B_Ural_Refuel_CDF",
	"CUP_B_Ural_Repair_CDF",
	"CUP_B_Ural_Open_CDF",
	"CUP_B_Ural_CDF",
	"CUP_B_AH6X_USA", //AH6X Littlebird ULB
	"CUP_B_Pchela1T_CDF", //Pchela-1T
	//Cup Veichles Armored
	"CUP_I_BTR40_MG_TKG",
	"CUP_I_BTR60_UN",
	"CUP_B_BRDM2_HQ_CZ",
	"CUP_B_BRDM2_CZ",
	"CUP_B_BAF_Coyote_GMG_W",
	"CUP_I_Datsun_PK",
	"CUP_B_Dingo_GL_CZ_Wdl",
	"CUP_B_Dingo_CZ_Wdl",
	"CUP_O_GAZ_Vodnik_PK_RU",
	"CUP_O_GAZ_Vodnik_AGS_RU",
	"CUP_O_GAZ_Vodnik_BPPU_RU",
	"CUP_B_HMMWV_Avenger_NATO_T",
	"CUP_B_HMMWV_Crows_M2_NATO_T",
	"CUP_B_HMMWV_Crows_MK19_NATO_T",
	"CUP_B_HMMWV_M2_GPK_NATO_T",
	"CUP_B_HMMWV_M2_NATO_T",
	"CUP_B_HMMWV_M1114_USMC",
	"CUP_B_HMMWV_MK19_NATO_T",
	"CUP_B_HMMWV_SOV_M2_NATO_T",
	"CUP_B_HMMWV_SOV_NATO_T",
	"CUP_B_HMMWV_TOW_NATO_T",
	"CUP_B_Jackal2_GMG_GB_W",
	"CUP_B_BAF_Coyote_L2A1_W",
	"CUP_B_Jackal2_L2A1_GB_W",
	"CUP_B_LR_MG_CZ_W",
	"CUP_B_LR_Special_CZ_W",
	"CUP_B_LAV25_USMC",
	"CUP_B_LAV25_HQ_USMC",
	"CUP_B_M1126_ICV_M2_Woodland_Slat",
	"CUP_B_M1126_ICV_M2_Woodland",
	"CUP_B_M1126_ICV_MK19_Woodland_Slat",
	"CUP_B_M1126_ICV_MK19_Woodland",
	"CUP_B_M1128_MGS_Woodland",
	"CUP_B_M1128_MGS_Woodland_Slat",
	"CUP_B_M1129_MC_MK19_Woodland_Slat",
	"CUP_B_M1129_MC_MK19_Woodland",
	"CUP_B_M1130_CV_M2_Woodland_Slat",
	"CUP_B_M1130_CV_M2_Woodland",
	"CUP_B_M1135_ATGMV_Woodland_Slat",
	"CUP_B_M1135_ATGMV_Woodland",
	"CUP_B_Mastiff_GMG_GB_W",
	"CUP_B_Mastiff_HMG_GB_W",
	"CUP_B_Mastiff_LMG_GB_W",
	"CUP_B_RG31_M2_GC_USMC",
	"CUP_B_RG31_M2_OD_USMC",
	"CUP_B_RG31_M2_USMC",
	"CUP_B_RG31_Mk19_OD_USMC",
	"CUP_B_RG31E_M2_USMC",
	"CUP_B_Ridgback_GMG_GB_W",
	"CUP_B_Ridgback_HMG_GB_W",
	"CUP_B_Ridgback_LMG_GB_W",
	"CUP_I_SUV_Armored_ION",
	"CUP_B_UAZ_AGS30_ACR",
	"CUP_B_UAZ_MG_ACR",
	"CUP_B_UAZ_METIS_ACR",
	"CUP_B_UAZ_SPG9_ACR",
	"CUP_B_Wolfhound_GMG_GB_W",
	"CUP_B_Wolfhound_HMG_GB_W",
	"CUP_B_Wolfhound_LMG_GB_W",
	// Cup Vehicles Tanks
	"CUP_O_2S6_RU",
	"CUP_B_AAV_USMC",
	"CUP_B_BMP_HQ_CDF",
	"CUP_B_BMP2_CDF",
	"CUP_B_Challenger2_Green_CTRG",
	"CUP_B_FV432_Bulldog_GB_W_RWS",
	"CUP_B_FV432_Bulldog_GB_W",
	"CUP_B_FV510_GB_W_SLAT",
	"CUP_B_FV510_GB_W",
	"CUP_B_M113_USA",
	"CUP_B_M163_USA",
	"CUP_B_M1A1_NATO_T",
	"CUP_B_M1A2_TUSK_MG_USMC",
	"CUP_B_M270_DPICM_USMC",
	"CUP_B_M270_HE_USMC",
	"CUP_B_M2Bradley_USA_W",
	"CUP_B_M2A3Bradley_USA_W",
	"CUP_B_M6LineBacker_USA_W",
	"CUP_B_M7Bradley_USA_D",
	"CUP_B_MCV80_GB_W_SLAT",
	"CUP_B_MCV80_GB_W",
	"CUP_I_T34_TK_GUE",
	"CUP_O_T55_CSAT",
	"CUP_B_T72_CDF",
	"CUP_B_T72_CZ",
	"CUP_O_T90_RU",
	"CUP_B_ZSU23_CDF",
	// Cup VEHICLE Helicopters
	"CUP_B_AH1_AT_BAF",
	"CUP_B_AH1_NO_BAF",
	"CUP_B_AH1_ES_BAF",
	"CUP_B_AH1_MR_BAF",
	"CUP_B_AH1_BAF",
	"CUP_B_AH1Z_AT_USMC",
	"CUP_B_AH1Z_USMC",
	"CUP_B_AH1Z_NoWeapons_USMC",
	"CUP_B_AH1Z_NOAA_USMC",
	"CUP_B_AH64D_AT_USA",
	"CUP_B_AH64D_NO_USA",
	"CUP_B_AH64D_ES_USA",
	"CUP_B_AH64D_MR_USA",
	"CUP_B_AH64D_USA",
	"CUP_B_AH6J_Cannons_USA",
	"CUP_B_AH6J_AT_USA",
	"CUP_B_AH6J_Escort_USA",
	"CUP_B_AH6J_Escort19_USA",
	"CUP_B_AH6J_AT_GAU_USA",
	"CUP_B_AH6J_Escort_GAU_USA",
	"CUP_B_AH6M_MP_USA",
	"CUP_B_AW159_Cannon_RN_Blackcat",
	"CUP_B_AW159_Unarmed_GB",
	"CUP_B_CH53E_GER",
	"CUP_B_CH47F_VIV_GB",
	"CUP_B_CH47F_GB",
	"CUP_B_Merlin_HC3_Armed_GB",
	"CUP_B_Merlin_HC3_GB",
	"CUP_B_MH60L_DAP_2x_AT_US",
	"CUP_B_MH60L_DAP_2x_Escort_US",
	"CUP_B_MH60L_DAP_2x_Multi_US",
	"CUP_B_MH60L_DAP_4x_AT_US",
	"CUP_B_MH60L_DAP_4x_Escort_US",
	"CUP_B_MH60L_DAP_4x_Multi_US",
	"CUP_B_MH6J_USA",
	"CUP_B_MH6M_USA",
	"CUP_B_Mi17_CDF",
	"CUP_B_Mi171Sh_ACR",
	"CUP_B_Mi171Sh_Unarmed_ACR",
	"CUP_B_Mi24_D_CDF",
	"CUP_B_Mi35_CZ_Ram",
	"CUP_B_MI6T_CDF",
	"CUP_B_SA330_Puma_HC1_BAF",
	"CUP_B_UH1D_GER_KSK",
	"CUP_B_UH1Y_GUNSHIP_USMC",
	"CUP_B_UH1Y_UNA_USMC",
	"CUP_B_UH60M_FFV_US",
	"CUP_B_UH60M_Unarmed_US",
	"CUP_B_UH60M_US",
	"CUP_O_Ka50_RU",
	"CUP_O_Ka50_AA_RU",
	//Cup vehicles Planes
	"CUP_C_AN2_CIV",
	"CUP_B_C130J_GB",
	"CUP_B_C47_USA",
	"CUP_B_AC47_Spooky_USA",
	"CUP_I_AV8B_MK82_AAF",
	"CUP_B_L39_CAP_CZ",
	"CUP_B_GR9_AGM_GB",
	"CUP_B_GR9_CAP_GB",
	"CUP_B_GR9_GBU12_GB",
	"CUP_B_GR9_Mk82_GB",
	"CUP_B_A10_AT_USA",
	"CUP_B_A10_CAS_USA",
	"CUP_B_F35B_AA_BAF",
	"CUP_B_F35B_CAS_BAF",
	"CUP_B_F35B_LGB_BAF",
	"CUP_B_USMC_MQ9",
	"CUP_O_Su25_RU_1",
	"CUP_O_SU34_AGM_RU",
	// Cup VEHICLE Boats
	"CUP_B_Zodiac_USMC",
	"CUP_B_RHIB_USMC",
	"CUP_B_RHIB2Turret_USMC",
	"CUP_B_Seafox_USV_USMC"
];

/**
 * List of class names of HEAVY towables objects. Takes precedence over R3F_LOG_CFG_objets_remorquables
 */
R3F_LOG_CFG_objets_remorquablesH =
[
	"Wheeled_APC_F",
	"Tank_F",
	"Heli_Attack_02_base_F",
	"Heli_Transport_01_base_F",
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F",
	"VTOL_base_F",
	"UAV_05_Base_F",
	"Plane_Fighter_01_Base_F",
	"Plane_Fighter_02_Base_F",
	"Plane_CAS_01_base_F",
	"Plane_CAS_02_base_F",
	//Cup Veichles Armored
	"CUP_I_BTR40_MG_TKG",
	"CUP_I_BTR60_UN",
	"CUP_B_BRDM2_HQ_CZ",
	"CUP_B_BRDM2_CZ",
	"CUP_B_BAF_Coyote_GMG_W",
	"CUP_I_Datsun_PK",
	"CUP_B_Dingo_GL_CZ_Wdl",
	"CUP_B_Dingo_CZ_Wdl",
	"CUP_O_GAZ_Vodnik_PK_RU",
	"CUP_O_GAZ_Vodnik_AGS_RU",
	"CUP_O_GAZ_Vodnik_BPPU_RU",
	"CUP_B_HMMWV_Avenger_NATO_T",
	"CUP_B_HMMWV_Crows_M2_NATO_T",
	"CUP_B_HMMWV_Crows_MK19_NATO_T",
	"CUP_B_HMMWV_M2_GPK_NATO_T",
	"CUP_B_HMMWV_M2_NATO_T",
	"CUP_B_HMMWV_M1114_USMC",
	"CUP_B_HMMWV_MK19_NATO_T",
	"CUP_B_HMMWV_SOV_M2_NATO_T",
	"CUP_B_HMMWV_SOV_NATO_T",
	"CUP_B_HMMWV_TOW_NATO_T",
	"CUP_B_Jackal2_GMG_GB_W",
	"CUP_B_BAF_Coyote_L2A1_W",
	"CUP_B_Jackal2_L2A1_GB_W",
	"CUP_B_LR_MG_CZ_W",
	"CUP_B_LR_Special_CZ_W",
	"CUP_B_LAV25_USMC",
	"CUP_B_LAV25_HQ_USMC",
	"CUP_B_M1126_ICV_M2_Woodland_Slat",
	"CUP_B_M1126_ICV_M2_Woodland",
	"CUP_B_M1126_ICV_MK19_Woodland_Slat",
	"CUP_B_M1126_ICV_MK19_Woodland",
	"CUP_B_M1128_MGS_Woodland",
	"CUP_B_M1128_MGS_Woodland_Slat",
	"CUP_B_M1129_MC_MK19_Woodland_Slat",
	"CUP_B_M1129_MC_MK19_Woodland",
	"CUP_B_M1130_CV_M2_Woodland_Slat",
	"CUP_B_M1130_CV_M2_Woodland",
	"CUP_B_M1135_ATGMV_Woodland_Slat",
	"CUP_B_M1135_ATGMV_Woodland",
	"CUP_B_Mastiff_GMG_GB_W",
	"CUP_B_Mastiff_HMG_GB_W",
	"CUP_B_Mastiff_LMG_GB_W",
	"CUP_B_RG31_M2_GC_USMC",
	"CUP_B_RG31_M2_OD_USMC",
	"CUP_B_RG31_M2_USMC",
	"CUP_B_RG31_Mk19_OD_USMC",
	"CUP_B_RG31E_M2_USMC",
	"CUP_B_Ridgback_GMG_GB_W",
	"CUP_B_Ridgback_HMG_GB_W",
	"CUP_B_Ridgback_LMG_GB_W",
	"CUP_I_SUV_Armored_ION",
	"CUP_B_UAZ_AGS30_ACR",
	"CUP_B_UAZ_MG_ACR",
	"CUP_B_UAZ_METIS_ACR",
	"CUP_B_UAZ_SPG9_ACR",
	"CUP_B_Wolfhound_GMG_GB_W",
	"CUP_B_Wolfhound_HMG_GB_W",
	"CUP_B_Wolfhound_LMG_GB_W",
	// Cup Vehicles Tanks
	"CUP_O_2S6_RU",
	"CUP_B_AAV_USMC",
	"CUP_B_BMP_HQ_CDF",
	"CUP_B_BMP2_CDF",
	"CUP_B_Challenger2_Green_CTRG",
	"CUP_B_FV432_Bulldog_GB_W_RWS",
	"CUP_B_FV432_Bulldog_GB_W",
	"CUP_B_FV510_GB_W_SLAT",
	"CUP_B_FV510_GB_W",
	"CUP_B_M113_USA",
	"CUP_B_M163_USA",
	"CUP_B_M1A1_NATO_T",
	"CUP_B_M1A2_TUSK_MG_USMC",
	"CUP_B_M270_DPICM_USMC",
	"CUP_B_M270_HE_USMC",
	"CUP_B_M2Bradley_USA_W",
	"CUP_B_M2A3Bradley_USA_W",
	"CUP_B_M6LineBacker_USA_W",
	"CUP_B_M7Bradley_USA_D",
	"CUP_B_MCV80_GB_W_SLAT",
	"CUP_B_MCV80_GB_W",
	"CUP_I_T34_TK_GUE",
	"CUP_O_T55_CSAT",
	"CUP_B_T72_CDF",
	"CUP_B_T72_CZ",
	"CUP_O_T90_RU",
	"CUP_B_ZSU23_CDF",
	// Cup VEHICLE Helicopters
	"CUP_B_AH1_AT_BAF",
	"CUP_B_AH1_NO_BAF",
	"CUP_B_AH1_ES_BAF",
	"CUP_B_AH1_MR_BAF",
	"CUP_B_AH1_BAF",
	"CUP_B_AH1Z_AT_USMC",
	"CUP_B_AH1Z_USMC",
	"CUP_B_AH1Z_NoWeapons_USMC",
	"CUP_B_AH1Z_NOAA_USMC",
	"CUP_B_AH64D_AT_USA",
	"CUP_B_AH64D_NO_USA",
	"CUP_B_AH64D_ES_USA",
	"CUP_B_AH64D_MR_USA",
	"CUP_B_AH64D_USA",
	"CUP_B_AH6J_Cannons_USA",
	"CUP_B_AH6J_AT_USA",
	"CUP_B_AH6J_Escort_USA",
	"CUP_B_AH6J_Escort19_USA",
	"CUP_B_AH6J_AT_GAU_USA",
	"CUP_B_AH6J_Escort_GAU_USA",
	"CUP_B_AH6M_MP_USA",
	"CUP_B_AW159_Cannon_RN_Blackcat",
	"CUP_B_AW159_Unarmed_GB",
	"CUP_B_CH53E_GER",
	"CUP_B_CH47F_VIV_GB",
	"CUP_B_CH47F_GB",
	"CUP_B_Merlin_HC3_Armed_GB",
	"CUP_B_Merlin_HC3_GB",
	"CUP_B_MH60L_DAP_2x_AT_US",
	"CUP_B_MH60L_DAP_2x_Escort_US",
	"CUP_B_MH60L_DAP_2x_Multi_US",
	"CUP_B_MH60L_DAP_4x_AT_US",
	"CUP_B_MH60L_DAP_4x_Escort_US",
	"CUP_B_MH60L_DAP_4x_Multi_US",
	"CUP_B_MH6J_USA",
	"CUP_B_MH6M_USA",
	"CUP_B_Mi17_CDF",
	"CUP_B_Mi171Sh_ACR",
	"CUP_B_Mi171Sh_Unarmed_ACR",
	"CUP_B_Mi24_D_CDF",
	"CUP_B_Mi35_CZ_Ram",
	"CUP_B_MI6T_CDF",
	"CUP_B_SA330_Puma_HC1_BAF",
	"CUP_B_UH1D_GER_KSK",
	"CUP_B_UH1Y_GUNSHIP_USMC",
	"CUP_B_UH1Y_UNA_USMC",
	"CUP_B_UH60M_FFV_US",
	"CUP_B_UH60M_Unarmed_US",
	"CUP_B_UH60M_US",
	"CUP_O_Ka50_RU",
	"CUP_O_Ka50_AA_RU",
	//Cup vehicles Planes
	"CUP_C_AN2_CIV",
	"CUP_B_C130J_GB",
	"CUP_B_C47_USA",
	"CUP_B_AC47_Spooky_USA",
	"CUP_I_AV8B_MK82_AAF",
	"CUP_B_L39_CAP_CZ",
	"CUP_B_GR9_AGM_GB",
	"CUP_B_GR9_CAP_GB",
	"CUP_B_GR9_GBU12_GB",
	"CUP_B_GR9_Mk82_GB",
	"CUP_B_A10_AT_USA",
	"CUP_B_A10_CAS_USA",
	"CUP_B_F35B_AA_BAF",
	"CUP_B_F35B_CAS_BAF",
	"CUP_B_F35B_LGB_BAF",
	"CUP_B_USMC_MQ9",
	"CUP_O_Su25_RU_1",
	"CUP_O_SU34_AGM_RU"
	// Cup VEHICLE Boats
	/*"CUP_B_Zodiac_USMC",
	"CUP_B_RHIB_USMC",
	"CUP_B_RHIB2Turret_USMC",
	"CUP_B_Seafox_USV_USMC"*/
];

R3F_LOG_CFG_objets_remorquables append R3F_LOG_CFG_objets_remorquablesH;

/****** LIFT WITH VEHICLE  ******/

/**
 * List of an lclass names of air vehicles which lift liftables objects.
 */
R3F_LOG_CFG_heliporteurs =
[
	// Cup VEHICLE Helicopters
	"CUP_B_AH1_AT_BAF",
	"CUP_B_AH1_NO_BAF",
	"CUP_B_AH1_ES_BAF",
	"CUP_B_AH1_MR_BAF",
	"CUP_B_AH1_BAF",
	"CUP_B_AH1Z_AT_USMC",
	"CUP_B_AH1Z_USMC",
	"CUP_B_AH1Z_NoWeapons_USMC",
	"CUP_B_AH1Z_NOAA_USMC",
	"CUP_B_AH64D_AT_USA",
	"CUP_B_AH64D_NO_USA",
	"CUP_B_AH64D_ES_USA",
	"CUP_B_AH64D_MR_USA",
	"CUP_B_AH64D_USA",
	"CUP_B_AH6J_Cannons_USA",
	"CUP_B_AH6J_AT_USA",
	"CUP_B_AH6J_Escort_USA",
	"CUP_B_AH6J_Escort19_USA",
	"CUP_B_AH6J_AT_GAU_USA",
	"CUP_B_AH6J_Escort_GAU_USA",
	"CUP_B_AH6M_MP_USA",
	"CUP_B_AW159_Cannon_RN_Blackcat",
	"CUP_B_AW159_Unarmed_GB",
	"CUP_B_CH53E_GER",
	"CUP_B_CH47F_VIV_GB",
	"CUP_B_CH47F_GB",
	"CUP_B_Merlin_HC3_Armed_GB",
	"CUP_B_Merlin_HC3_GB",
	"CUP_B_MH60L_DAP_2x_AT_US",
	"CUP_B_MH60L_DAP_2x_Escort_US",
	"CUP_B_MH60L_DAP_2x_Multi_US",
	"CUP_B_MH60L_DAP_4x_AT_US",
	"CUP_B_MH60L_DAP_4x_Escort_US",
	"CUP_B_MH60L_DAP_4x_Multi_US",
	"CUP_B_MH6J_USA",
	"CUP_B_MH6M_USA",
	"CUP_B_Mi17_CDF",
	"CUP_B_Mi171Sh_ACR",
	"CUP_B_Mi171Sh_Unarmed_ACR",
	"CUP_B_Mi24_D_CDF",
	"CUP_B_Mi35_CZ_Ram",
	"CUP_B_MI6T_CDF",
	"CUP_B_SA330_Puma_HC1_BAF",
	"CUP_B_UH1D_GER_KSK",
	"CUP_B_UH1Y_GUNSHIP_USMC",
	"CUP_B_UH1Y_UNA_USMC",
	"CUP_B_UH60M_FFV_US",
	"CUP_B_UH60M_Unarmed_US",
	"CUP_B_UH60M_US",
	"CUP_O_Ka50_RU",
	"CUP_O_Ka50_AA_RU",
	//"Helicopter_Base_F"
	//"Heli_Light_01_base_F",
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"Heli_Attack_01_base_F",
	"Heli_Attack_02_base_F",
	"Heli_Transport_01_base_F",
	"VTOL_base_F"
];

/**
 * List of class names of HEAVY air vehicles which can lift heavy liftables objects. Takes precedence over R3F_LOG_CFG_objets_remorquables
 */
R3F_LOG_CFG_heliporteursH =
[
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F",
	"CUP_B_CH53E_GER",
	"CUP_B_CH47F_VIV_GB",
	"CUP_B_CH47F_GB",
	"CUP_B_MI6T_CDF"
];

R3F_LOG_CFG_heliporteurs append R3F_LOG_CFG_heliporteursH;

/**
 * List of class names of liftables objects.
 */
R3F_LOG_CFG_objets_heliportables =
[
	"Car_F",
	"Ship_F",
	"Plane",
	"UAV_03_base_F",
	"Heli_Light_01_base_F",
	//Cup VEHICLE
	"CUP_C_Skoda_Blue_CIV",
	"CUP_C_Datsun_Covered",
	"CUP_C_Datsun_Plain",
	"CUP_C_Datsun_Tubeframe",
	"CUP_C_Golf4_red_Civ", 
	"CUP_C_Ikarus_Chernarus",
	"CUP_I_BTR40_TKG", 
	"CUP_B_HMMWV_Transport_NATO_T",
	"CUP_B_HMMWV_Terminal_NATO_T",
	"CUP_B_HMMWV_Unarmed_NATO_T",
	"CUP_B_HMMWV_Ambulance_ACR",
	"CUP_O_GAZ_Vodnik_MedEvac_RU",
	"CUP_B_LR_Ambulance_CZ_D",
	"CUP_B_LR_Ambulance_CZ_W",
	"CUP_B_LR_Transport_CZ_D",
	"CUP_B_LR_Transport_CZ_W",
	//"CUP_B_M1030_USMC",
	"CUP_B_M1133_MEV_Woodland",
	"CUP_B_M1133_MEV_Woodland_Slat",
	"CUP_B_M113_Med_USA",
	"CUP_B_MTVR_Ammo_USA",
	"CUP_B_MTVR_Refuel_USA",
	"CUP_B_MTVR_Repair_USA",
	"CUP_B_MTVR_USA",
	"CUP_B_T810_Reammo_CZ_WDL",
	"CUP_B_T810_Unarmed_CZ_WDL",
	"CUP_B_T810_Refuel_CZ_WDL",
	"CUP_B_T810_Repair_CZ_WDL",
	"CUP_B_TowingTractor_USMC",
	"CUP_I_SUV_ION",
	"CUP_B_UAZ_Open_ACR",
	"CUP_B_UAZ_Unarmed_ACR",
	"CUP_B_Ural_Reammo_CDF",
	"CUP_B_Ural_Empty_CDF",
	"CUP_B_Ural_Refuel_CDF",
	"CUP_B_Ural_Repair_CDF",
	"CUP_B_Ural_Open_CDF",
	"CUP_B_Ural_CDF",
	//"CUP_B_AH6X_USA", //AH6X Littlebird ULB
	//"CUP_B_Pchela1T_CDF", //Pchela-1T
	//Cup Veichles Armored
	"CUP_I_BTR40_MG_TKG",
	"CUP_I_BTR60_UN",
	"CUP_B_BRDM2_HQ_CZ",
	"CUP_B_BRDM2_CZ",
	"CUP_B_BAF_Coyote_GMG_W",
	"CUP_I_Datsun_PK",
	"CUP_B_Dingo_GL_CZ_Wdl",
	"CUP_B_Dingo_CZ_Wdl",
	"CUP_O_GAZ_Vodnik_PK_RU",
	"CUP_O_GAZ_Vodnik_AGS_RU",
	"CUP_O_GAZ_Vodnik_BPPU_RU",
	"CUP_B_HMMWV_Avenger_NATO_T",
	"CUP_B_HMMWV_Crows_M2_NATO_T",
	"CUP_B_HMMWV_Crows_MK19_NATO_T",
	"CUP_B_HMMWV_M2_GPK_NATO_T",
	"CUP_B_HMMWV_M2_NATO_T",
	"CUP_B_HMMWV_M1114_USMC",
	"CUP_B_HMMWV_MK19_NATO_T",
	"CUP_B_HMMWV_SOV_M2_NATO_T",
	"CUP_B_HMMWV_SOV_NATO_T",
	"CUP_B_HMMWV_TOW_NATO_T",
	"CUP_B_Jackal2_GMG_GB_W",
	"CUP_B_BAF_Coyote_L2A1_W",
	"CUP_B_Jackal2_L2A1_GB_W",
	"CUP_B_LR_MG_CZ_W",
	"CUP_B_LR_Special_CZ_W",
	"CUP_B_LAV25_USMC",
	"CUP_B_LAV25_HQ_USMC",
	"CUP_B_M1126_ICV_M2_Woodland_Slat",
	"CUP_B_M1126_ICV_M2_Woodland",
	"CUP_B_M1126_ICV_MK19_Woodland_Slat",
	"CUP_B_M1126_ICV_MK19_Woodland",
	"CUP_B_M1128_MGS_Woodland",
	"CUP_B_M1128_MGS_Woodland_Slat",
	"CUP_B_M1129_MC_MK19_Woodland_Slat",
	"CUP_B_M1129_MC_MK19_Woodland",
	"CUP_B_M1130_CV_M2_Woodland_Slat",
	"CUP_B_M1130_CV_M2_Woodland",
	"CUP_B_M1135_ATGMV_Woodland_Slat",
	"CUP_B_M1135_ATGMV_Woodland",
	"CUP_B_Mastiff_GMG_GB_W",
	"CUP_B_Mastiff_HMG_GB_W",
	"CUP_B_Mastiff_LMG_GB_W",
	"CUP_B_RG31_M2_GC_USMC",
	"CUP_B_RG31_M2_OD_USMC",
	"CUP_B_RG31_M2_USMC",
	"CUP_B_RG31_Mk19_OD_USMC",
	"CUP_B_RG31E_M2_USMC",
	"CUP_B_Ridgback_GMG_GB_W",
	"CUP_B_Ridgback_HMG_GB_W",
	"CUP_B_Ridgback_LMG_GB_W",
	"CUP_I_SUV_Armored_ION",
	"CUP_B_UAZ_AGS30_ACR",
	"CUP_B_UAZ_MG_ACR",
	"CUP_B_UAZ_METIS_ACR",
	"CUP_B_UAZ_SPG9_ACR",
	"CUP_B_Wolfhound_GMG_GB_W",
	"CUP_B_Wolfhound_HMG_GB_W",
	"CUP_B_Wolfhound_LMG_GB_W",
	// Cup Vehicles Tanks
	/*"CUP_O_2S6_RU",
	"CUP_B_AAV_USMC",
	"CUP_B_BMP_HQ_CDF",
	"CUP_B_BMP2_CDF",
	"CUP_B_Challenger2_Green_CTRG",
	"CUP_B_FV432_Bulldog_GB_W_RWS",
	"CUP_B_FV432_Bulldog_GB_W",
	"CUP_B_FV510_GB_W_SLAT",
	"CUP_B_FV510_GB_W",
	"CUP_B_M113_USA",
	"CUP_B_M163_USA",
	"CUP_B_M1A1_NATO_T",
	"CUP_B_M1A2_TUSK_MG_USMC",
	"CUP_B_M270_DPICM_USMC",
	"CUP_B_M270_HE_USMC",
	"CUP_B_M2Bradley_USA_W",
	"CUP_B_M2A3Bradley_USA_W",
	"CUP_B_M6LineBacker_USA_W",
	"CUP_B_M7Bradley_USA_D",
	"CUP_B_MCV80_GB_W_SLAT",
	"CUP_B_MCV80_GB_W",
	"CUP_I_T34_TK_GUE",
	"CUP_O_T55_CSAT",
	"CUP_B_T72_CDF",
	"CUP_B_T72_CZ",
	"CUP_O_T90_RU",
	"CUP_B_ZSU23_CDF",*/
	// Cup VEHICLE Helicopters
	"CUP_B_AH1_AT_BAF",
	"CUP_B_AH1_NO_BAF",
	"CUP_B_AH1_ES_BAF",
	"CUP_B_AH1_MR_BAF",
	"CUP_B_AH1_BAF",
	"CUP_B_AH1Z_AT_USMC",
	"CUP_B_AH1Z_USMC",
	"CUP_B_AH1Z_NoWeapons_USMC",
	"CUP_B_AH1Z_NOAA_USMC",
	"CUP_B_AH64D_AT_USA",
	"CUP_B_AH64D_NO_USA",
	"CUP_B_AH64D_ES_USA",
	"CUP_B_AH64D_MR_USA",
	"CUP_B_AH64D_USA",
	"CUP_B_AH6J_Cannons_USA",
	"CUP_B_AH6J_AT_USA",
	"CUP_B_AH6J_Escort_USA",
	"CUP_B_AH6J_Escort19_USA",
	"CUP_B_AH6J_AT_GAU_USA",
	"CUP_B_AH6J_Escort_GAU_USA",
	"CUP_B_AH6M_MP_USA",
	"CUP_B_AW159_Cannon_RN_Blackcat",
	"CUP_B_AW159_Unarmed_GB",
	"CUP_B_CH53E_GER",
	"CUP_B_CH47F_VIV_GB",
	"CUP_B_CH47F_GB",
	"CUP_B_Merlin_HC3_Armed_GB",
	"CUP_B_Merlin_HC3_GB",
	"CUP_B_MH60L_DAP_2x_AT_US",
	"CUP_B_MH60L_DAP_2x_Escort_US",
	"CUP_B_MH60L_DAP_2x_Multi_US",
	"CUP_B_MH60L_DAP_4x_AT_US",
	"CUP_B_MH60L_DAP_4x_Escort_US",
	"CUP_B_MH60L_DAP_4x_Multi_US",
	"CUP_B_MH6J_USA",
	"CUP_B_MH6M_USA",
	"CUP_B_Mi17_CDF",
	"CUP_B_Mi171Sh_ACR",
	"CUP_B_Mi171Sh_Unarmed_ACR",
	"CUP_B_Mi24_D_CDF",
	"CUP_B_Mi35_CZ_Ram",
	"CUP_B_MI6T_CDF",
	"CUP_B_SA330_Puma_HC1_BAF",
	"CUP_B_UH1D_GER_KSK",
	"CUP_B_UH1Y_GUNSHIP_USMC",
	"CUP_B_UH1Y_UNA_USMC",
	"CUP_B_UH60M_FFV_US",
	"CUP_B_UH60M_Unarmed_US",
	"CUP_B_UH60M_US",
	"CUP_O_Ka50_RU",
	"CUP_O_Ka50_AA_RU",
	//Cup vehicles Planes
	"CUP_C_AN2_CIV",
	"CUP_B_C130J_GB",
	"CUP_B_C47_USA",
	"CUP_B_AC47_Spooky_USA",
	"CUP_I_AV8B_MK82_AAF",
	"CUP_B_L39_CAP_CZ",
	"CUP_B_GR9_AGM_GB",
	"CUP_B_GR9_CAP_GB",
	"CUP_B_GR9_GBU12_GB",
	"CUP_B_GR9_Mk82_GB",
	"CUP_B_A10_AT_USA",
	"CUP_B_A10_CAS_USA",
	"CUP_B_F35B_AA_BAF",
	"CUP_B_F35B_CAS_BAF",
	"CUP_B_F35B_LGB_BAF",
	"CUP_B_USMC_MQ9",
	"CUP_O_Su25_RU_1",
	"CUP_O_SU34_AGM_RU",
	// Cup VEHICLE Boats
	"CUP_B_Zodiac_USMC",
	"CUP_B_RHIB_USMC",
	"CUP_B_RHIB2Turret_USMC",
	"CUP_B_Seafox_USV_USMC"
];

/**
 * List of class names of HEAVY liftables objects. Takes precedence over R3F_LOG_CFG_objets_heliportables
 */
R3F_LOG_CFG_objets_heliportablesH =
[
	"Wheeled_APC_F",
	"Tank_F",
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"Heli_Attack_01_base_F",
	"Heli_Attack_02_base_F",
	"Heli_Transport_01_base_F",
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F",
	"Plane_CAS_01_base_F",
	"Plane_CAS_02_base_F",
	"Plane_Fighter_03_base_F",
	"VTOL_01_base_F",
	"VTOL_02_base_F",
	// Cup Vehicles Tanks
	"CUP_O_2S6_RU",
	"CUP_B_AAV_USMC",
	"CUP_B_BMP_HQ_CDF",
	"CUP_B_BMP2_CDF",
	"CUP_B_Challenger2_Green_CTRG",
	"CUP_B_FV432_Bulldog_GB_W_RWS",
	"CUP_B_FV432_Bulldog_GB_W",
	"CUP_B_FV510_GB_W_SLAT",
	"CUP_B_FV510_GB_W",
	"CUP_B_M113_USA",
	"CUP_B_M163_USA",
	"CUP_B_M1A1_NATO_T",
	"CUP_B_M1A2_TUSK_MG_USMC",
	"CUP_B_M270_DPICM_USMC",
	"CUP_B_M270_HE_USMC",
	"CUP_B_M2Bradley_USA_W",
	"CUP_B_M2A3Bradley_USA_W",
	"CUP_B_M6LineBacker_USA_W",
	"CUP_B_M7Bradley_USA_D",
	"CUP_B_MCV80_GB_W_SLAT",
	"CUP_B_MCV80_GB_W",
	"CUP_I_T34_TK_GUE",
	"CUP_O_T55_CSAT",
	"CUP_B_T72_CDF",
	"CUP_B_T72_CZ",
	"CUP_O_T90_RU",
	"CUP_B_ZSU23_CDF"
	
];

R3F_LOG_CFG_objets_heliportables append R3F_LOG_CFG_objets_heliportablesH;


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/


/**
 * List of class names of (ground or air) vehicles which can transport transportables objects.
 * The second element of the arrays is the load capacity (in relation with the capacity cost of the objects).
 */
R3F_LOG_CFG_transporteurs =
[
	//Cup Veichles Unarmed
	["CUP_C_Skoda_Blue_CIV", 10],
	["CUP_C_Datsun_Covered", 20],
	["CUP_C_Datsun_Plain", 15],
	["CUP_C_Datsun_Tubeframe", 15],
	["CUP_C_Golf4_red_Civ", 20],
	["CUP_C_Ikarus_Chernarus", 200],
	["CUP_I_BTR40_TKG", 40],
	["CUP_B_HMMWV_Transport_NATO_T", 30],
	["CUP_B_HMMWV_Terminal_NATO_T", 50],
	["CUP_B_HMMWV_Unarmed_NATO_T", 25],
	["CUP_B_HMMWV_Ambulance_ACR", 35],
	["CUP_O_GAZ_Vodnik_MedEvac_RU", 35],
	["CUP_B_LR_Ambulance_CZ_D", 50],
	["CUP_B_LR_Ambulance_CZ_W", 50],
	["CUP_B_LR_Transport_CZ_D", 40],
	["CUP_B_LR_Transport_CZ_W", 40],
	["CUP_B_M1030_USMC", 5],
	["CUP_B_M1133_MEV_Woodland", 75],
	["CUP_B_M1133_MEV_Woodland_Slat", 75],
	["CUP_B_M113_Med_USA", 75],
	["CUP_B_MTVR_Ammo_USA", 75],
	["CUP_B_MTVR_Refuel_USA", 75],
	["CUP_B_MTVR_Repair_USA", 75],
	["CUP_B_MTVR_USA", 85],
	["CUP_B_T810_Reammo_CZ_WDL", 75],
	["CUP_B_T810_Unarmed_CZ_WDL", 85],
	["CUP_B_T810_Refuel_CZ_WDL", 75],
	["CUP_B_T810_Repair_CZ_WDL", 75],
	["CUP_B_TowingTractor_USMC", 30],
	["CUP_I_SUV_ION", 35],
	["CUP_B_UAZ_Open_ACR", 20],
	["CUP_B_UAZ_Unarmed_ACR", 25],
	["CUP_B_Ural_Reammo_CDF", 75],
	["CUP_B_Ural_Empty_CDF", 85],
	["CUP_B_Ural_Refuel_CDF", 75],
	["CUP_B_Ural_Repair_CDF", 75],
	["CUP_B_Ural_Open_CDF", 85],
	["CUP_B_Ural_CDF", 85],
	["CUP_B_AH6X_USA", 20], //AH6X Littlebird ULB
	["CUP_B_Pchela1T_CDF", 10], //Pchela-1T
	//Cup Veichles Armored
	["CUP_I_BTR40_MG_TKG", 80],
	["CUP_I_BTR60_UN", 85],
	["CUP_B_BRDM2_HQ_CZ", 80],
	["CUP_B_BRDM2_CZ", 85],
	["CUP_B_BAF_Coyote_GMG_W", 80],
	["CUP_I_Datsun_PK", 55],
	["CUP_B_Dingo_GL_CZ_Wdl", 100],
	["CUP_B_Dingo_CZ_Wdl", 100],
	["CUP_O_GAZ_Vodnik_PK_RU", 55],
	["CUP_O_GAZ_Vodnik_AGS_RU", 55],
	["CUP_O_GAZ_Vodnik_BPPU_RU", 55],
	["CUP_B_HMMWV_Avenger_NATO_T", 55],
	["CUP_B_HMMWV_Crows_M2_NATO_T", 50],
	["CUP_B_HMMWV_Crows_MK19_NATO_T", 50],
	["CUP_B_HMMWV_M2_GPK_NATO_T", 50],
	["CUP_B_HMMWV_M2_NATO_T", 50],
	["CUP_B_HMMWV_M1114_USMC", 50],
	["CUP_B_HMMWV_MK19_NATO_T", 50],
	["CUP_B_HMMWV_SOV_M2_NATO_T", 50],
	["CUP_B_HMMWV_SOV_NATO_T", 50],
	["CUP_B_HMMWV_TOW_NATO_T", 50],
	["CUP_B_Jackal2_GMG_GB_W", 80],
	["CUP_B_BAF_Coyote_L2A1_W", 80],
	["CUP_B_Jackal2_L2A1_GB_W", 80],
	["CUP_B_LR_MG_CZ_W", 55],
	["CUP_B_LR_Special_CZ_W", 60],
	["CUP_B_LAV25_USMC", 80],
	["CUP_B_LAV25_HQ_USMC", 80],
	["CUP_B_M1126_ICV_M2_Woodland_Slat", 80],
	["CUP_B_M1126_ICV_M2_Woodland", 75],
	["CUP_B_M1126_ICV_MK19_Woodland_Slat", 75],
	["CUP_B_M1126_ICV_MK19_Woodland", 75],
	["CUP_B_M1128_MGS_Woodland", 80],
	["CUP_B_M1128_MGS_Woodland_Slat", 80],
	["CUP_B_M1129_MC_MK19_Woodland_Slat", 85],
	["CUP_B_M1129_MC_MK19_Woodland", 85],
	["CUP_B_M1130_CV_M2_Woodland_Slat", 85],
	["CUP_B_M1130_CV_M2_Woodland", 85],
	["CUP_B_M1135_ATGMV_Woodland_Slat", 90],
	["CUP_B_M1135_ATGMV_Woodland", 95],
	["CUP_B_Mastiff_GMG_GB_W", 65],
	["CUP_B_Mastiff_HMG_GB_W", 55],
	["CUP_B_Mastiff_LMG_GB_W", 55],
	["CUP_B_RG31_M2_GC_USMC", 80],
	["CUP_B_RG31_M2_OD_USMC", 80],
	["CUP_B_RG31_M2_USMC", 75],
	["CUP_B_RG31_Mk19_OD_USMC", 85],
	["CUP_B_RG31E_M2_USMC", 80],
	["CUP_B_Ridgback_GMG_GB_W", 60],
	["CUP_B_Ridgback_HMG_GB_W", 50],
	["CUP_B_Ridgback_LMG_GB_W", 50],
	["CUP_I_SUV_Armored_ION", 35],
	["CUP_B_UAZ_AGS30_ACR", 80],
	["CUP_B_UAZ_MG_ACR", 70],
	["CUP_B_UAZ_METIS_ACR", 60],
	["CUP_B_UAZ_SPG9_ACR", 60],
	["CUP_B_Wolfhound_GMG_GB_W", 55],
	["CUP_B_Wolfhound_HMG_GB_W", 45],
	["CUP_B_Wolfhound_LMG_GB_W", 45],
	// Cup Vehicles Tanks
	["CUP_O_2S6_RU", 95],
	["CUP_B_AAV_USMC", 95],
	["CUP_B_BMP_HQ_CDF", 80],
	["CUP_B_BMP2_CDF", 75],
	["CUP_B_Challenger2_Green_CTRG", 60],
	["CUP_B_FV432_Bulldog_GB_W_RWS", 75],
	["CUP_B_FV432_Bulldog_GB_W", 60],
	["CUP_B_FV510_GB_W_SLAT", 60],
	["CUP_B_FV510_GB_W", 75],
	["CUP_B_M113_USA", 70],
	["CUP_B_M163_USA", 75],
	["CUP_B_M1A1_NATO_T", 95],
	["CUP_B_M1A2_TUSK_MG_USMC", 95],
	["CUP_B_M270_DPICM_USMC", 85],
	["CUP_B_M270_HE_USMC", 85],
	["CUP_B_M2Bradley_USA_W", 55],
	["CUP_B_M2A3Bradley_USA_W", 55],
	["CUP_B_M6LineBacker_USA_W", 65],
	["CUP_B_M7Bradley_USA_D", 55],
	["CUP_B_MCV80_GB_W_SLAT", 75],
	["CUP_B_MCV80_GB_W", 85],
	["CUP_I_T34_TK_GUE", 75],
	["CUP_O_T55_CSAT", 55],
	["CUP_B_T72_CDF", 65],
	["CUP_B_T72_CZ", 75],
	["CUP_O_T90_RU", 80],
	["CUP_B_ZSU23_CDF", 90],
	// Cup VEHICLE Helicopters
	["CUP_B_AH1_AT_BAF", 30],
	["CUP_B_AH1_NO_BAF", 35],
	["CUP_B_AH1_ES_BAF", 30],
	["CUP_B_AH1_MR_BAF", 30],
	["CUP_B_AH1_BAF", 30],
	["CUP_B_AH1Z_AT_USMC", 35],
	["CUP_B_AH1Z_USMC", 35],
	["CUP_B_AH1Z_NoWeapons_USMC", 35],
	["CUP_B_AH1Z_NOAA_USMC", 35],
	["CUP_B_AH64D_AT_USA", 35],
	["CUP_B_AH64D_NO_USA", 40],
	["CUP_B_AH64D_ES_USA", 35],
	["CUP_B_AH64D_MR_USA", 35],
	["CUP_B_AH64D_USA", 30],
	["CUP_B_AH6J_Cannons_USA", 35],
	["CUP_B_AH6J_AT_USA", 30],
	["CUP_B_AH6J_Escort_USA", 30],
	["CUP_B_AH6J_Escort19_USA", 30],
	["CUP_B_AH6J_AT_GAU_USA", 30],
	["CUP_B_AH6J_Escort_GAU_USA", 25],
	["CUP_B_AH6M_MP_USA", 30],
	["CUP_B_AW159_Cannon_RN_Blackcat", 30],
	["CUP_B_AW159_Unarmed_GB", 35],
	["CUP_B_CH53E_GER", 30],
	["CUP_B_CH47F_VIV_GB", 55],
	["CUP_B_CH47F_GB", 55],
	["CUP_B_Merlin_HC3_Armed_GB", 55],
	["CUP_B_Merlin_HC3_GB", 55],
	["CUP_B_MH60L_DAP_2x_AT_US", 30],
	["CUP_B_MH60L_DAP_2x_Escort_US", 30],
	["CUP_B_MH60L_DAP_2x_Multi_US", 30],
	["CUP_B_MH60L_DAP_4x_AT_US", 30],
	["CUP_B_MH60L_DAP_4x_Escort_US", 30],
	["CUP_B_MH60L_DAP_4x_Multi_US", 30],
	["CUP_B_MH6J_USA", 20],
	["CUP_B_MH6M_USA", 25],
	["CUP_B_Mi17_CDF", 55],
	["CUP_B_Mi171Sh_ACR", 55],
	["CUP_B_Mi171Sh_Unarmed_ACR", 55],
	["CUP_B_Mi24_D_CDF", 55],
	["CUP_B_Mi35_CZ_Ram", 55],
	["CUP_B_MI6T_CDF", 55],
	["CUP_B_SA330_Puma_HC1_BAF", 55],
	["CUP_B_UH1D_GER_KSK", 20],
	["CUP_B_UH1Y_GUNSHIP_USMC", 25],
	["CUP_B_UH1Y_UNA_USMC", 25],
	["CUP_B_UH60M_FFV_US", 30],
	["CUP_B_UH60M_Unarmed_US", 35],
	["CUP_B_UH60M_US", 35],
	["CUP_O_Ka50_RU", 35],
	["CUP_O_Ka50_AA_RU", 40],
	//Cup vehicles Planes
	["CUP_C_AN2_CIV", 30],
	["CUP_B_C130J_GB", 40],
	["CUP_B_C47_USA", 30],
	["CUP_B_AC47_Spooky_USA", 35],
	["CUP_I_AV8B_MK82_AAF", 35],
	["CUP_B_L39_CAP_CZ", 30],
	["CUP_B_GR9_AGM_GB", 30],
	["CUP_B_GR9_CAP_GB", 30],
	["CUP_B_GR9_GBU12_GB", 30],
	["CUP_B_GR9_Mk82_GB", 30],
	["CUP_B_A10_AT_USA", 30],
	["CUP_B_A10_CAS_USA", 30],
	["CUP_B_F35B_AA_BAF", 30],
	["CUP_B_F35B_CAS_BAF", 30],
	["CUP_B_F35B_LGB_BAF", 30],
	["CUP_B_USMC_MQ9", 30],
	["CUP_O_Su25_RU_1", 30],
	["CUP_O_SU34_AGM_RU", 30],
	// Cup VEHICLE Boats
	["CUP_B_Zodiac_USMC", 20],
	["CUP_B_RHIB_USMC", 20],
	["CUP_B_RHIB2Turret_USMC", 20],
	["CUP_B_Seafox_USV_USMC", 20],
	
	//Arma 3
	["Quadbike_01_base_F", 5],
	["UGV_01_base_F", 10],
	["Hatchback_01_base_F", 10],
	["SUV_01_base_F", 20],
	["Offroad_01_base_F", 30],
	["Offroad_02_base_F", 20],
	["Van_01_base_F", 40],
	["Van_02_base_F", 50],
	["LSV_01_base_F", 15],
	["LSV_02_base_F", 15],
	["MRAP_01_base_F", 20],
	["MRAP_02_base_F", 20],
	["MRAP_03_base_F", 20],
	["B_Truck_01_box_F", 150],
	["Truck_F", 75],
	["Wheeled_APC_F", 30],
	["Tank_F", 30],
	["Scooter_Transport_01_base_F", 5],
	["SDV_01_base_F", 10],
	["Rubber_duck_base_F", 10],
	["Boat_Civil_01_base_F", 10],
	["Boat_Transport_02_base_F", 15],
	["Boat_Armed_01_base_F", 20],
	["Heli_Light_01_base_F", 10],
	["Heli_Light_02_base_F", 20],
	["Heli_light_03_base_F", 20],
	["Heli_Transport_01_base_F", 25],
	["Heli_Transport_02_base_F", 30],
	["Heli_Transport_03_base_F", 30],
	["Heli_Transport_04_base_F", 30],
	["Heli_Attack_01_base_F", 10],
	["Heli_Attack_02_base_F", 20],
	["Plane_Civil_01_base_F", 5],
	["VTOL_01_base_F", 50],
	["VTOL_02_base_F", 30]
];


R3F_LOG_CFG_objets_transportables =
[
	["Land_AirConditioner_01_F", 5],           //Re Locker
	["Land_Mil_WallBig_4m_F", 1],           //Base Door (Pillbox)
    ["Land_Canal_Wall_10m_F", 15],              //Base Door (Canal Wall)
    ["Land_DataTerminal_01_F", 1],      //Base Door Key
	["Box_IDAP_Equip_F", 10],                    //Safe
	["Static_Designator_01_base_F", 2],
	["Static_Designator_02_base_F", 2],
	["StaticWeapon", 5],
	["Box_NATO_AmmoVeh_F", 10],
	["B_supplyCrate_F", 5],
	["ReammoBox_F", 3],
	["Kart_01_Base_F", 5],
	["Quadbike_01_base_F", 10],
	["CUP_B_M1030_USMC", 10],
	["Rubber_duck_base_F", 10],
	["UAV_01_base_F", 2],
	["UAV_06_base_F", 2],
	["Land_PierLadder_F", 3],
	["Land_BagBunker_Large_F", 10],
	["Land_BagBunker_Small_F", 5],
	["Land_BagBunker_Tower_F", 7],
	["Land_BagFence_Corner_F", 2],
	["Land_BagFence_End_F", 2],
	["Land_BagFence_Long_F", 3],
	["Land_BagFence_Round_F", 2],
	["Land_BagFence_Short_F", 2],
	["Land_BarGate_F", 3],
	["Land_Canal_WallSmall_10m_F", 4],
	["Land_Canal_Wall_Stairs_F", 3],
	["Land_CargoBox_V1_F", 5],
	["Land_Cargo_Patrol_V1_F", 7],
	["Land_Cargo_Tower_V1_F", 30],
	["Land_CncBarrier_F", 4],
	["Land_CncBarrierMedium_F", 4],
	["Land_CncBarrierMedium4_F", 4],
	["Land_CncShelter_F", 2],
	["Land_CncWall1_F", 3],
	["Land_CncWall4_F", 5],
	["Land_Crash_barrier_F", 5],
	["Land_HBarrierBig_F", 5],
	["Land_HBarrierTower_F", 8],
	["Land_HBarrierWall4_F", 4],
	["Land_HBarrierWall6_F", 6],
	["Land_HBarrier_1_F", 3],
	["Land_HBarrier_3_F", 4],
	["Land_HBarrier_5_F", 5],
	["Land_LampHarbour_F", 2],
	["Land_LampShabby_F", 2],
	["Land_MetalBarrel_F", 2],
	["Land_Mil_ConcreteWall_F", 5],
	["Land_Mil_WallBig_4m_F", 5],
	["Land_Obstacle_Ramp_F", 5],
	["Land_Pipes_large_F", 5],
	["Land_RampConcreteHigh_F", 6],
	["Land_RampConcrete_F", 5],
	["Land_Razorwire_F", 5],
	["Land_Sacks_goods_F", 2],
	["Land_Scaffolding_F", 5],
	["Land_Shoot_House_Wall_F", 3],
	["Land_Stone_8m_F", 5],
	["Land_ToiletBox_F", 2],
	["Land_BarrelWater_F", 2],
	["Campfire_burning_F", 2],
	["Land_CampingChair_V1_F", 2],
	["Land_CampingTable_F", 2]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

R3F_LOG_CFG_objets_deplacables =
[
	"Land_AirConditioner_01_F", //relocker
	"Land_Mil_WallBig_4m_F",         //Base Door
    "Land_DataTerminal_01_F",   //Base Door Key
	"Box_IDAP_Equip_F",
	"B_supplyCrate_F",
	"Box_NATO_Wps_F",
	"Box_NATO_WpsSpecial_F",
	"Box_East_Wps_F",
	"Box_East_WpsSpecial_F",
	"Box_IND_Wps_F",
	"Box_IND_WpsSpecial_F",
	"Box_FIA_Support_F",
	"Box_FIA_Wps_F",
	"Box_FIA_Ammo_F",
	"StaticWeapon",
	"Kart_01_Base_F",
	"Quadbike_01_base_F",
	"CUP_B_M1030_USMC",
	"Rubber_duck_base_F",
	"SDV_01_base_F",
	"UAV_01_base_F",
	"UAV_06_base_F",
	"Land_PierLadder_F",
	"Land_BagBunker_Large_F",
	"Land_BagBunker_Small_F",
	"Land_BagBunker_Tower_F",
	"Land_BagFence_Corner_F",
	"Land_BagFence_End_F",
	"Land_BagFence_Long_F",
	"Land_BagFence_Round_F",
	"Land_BagFence_Short_F",
	"Land_BarGate_F",
	"Land_Canal_WallSmall_10m_F",
	"Land_Canal_Wall_Stairs_F",
	"Land_CargoBox_V1_F",
	"Land_Cargo_Patrol_V1_F",
	"Land_Cargo_Tower_V1_F",
	"Land_CncBarrier_F",
	"Land_CncBarrierMedium_F",
	"Land_CncBarrierMedium4_F",
	"Land_CncShelter_F",
	"Land_CncWall1_F",
	"Land_CncWall4_F",
	"Land_Crash_barrier_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierTower_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall6_F",
	"Land_HBarrier_1_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_LampHarbour_F",
	"Land_LampShabby_F",
	"Land_MetalBarrel_F",
	"Land_Mil_ConcreteWall_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Obstacle_Ramp_F",
	"Land_Pipes_large_F",
	"Land_RampConcreteHigh_F",
	"Land_RampConcrete_F",
	"Land_Razorwire_F",
	"Land_Sacks_goods_F",
	"Land_Scaffolding_F",
	"Land_Shoot_House_Wall_F",
	"Land_Stone_8m_F",
	"Land_ToiletBox_F",
	"Land_BarrelWater_F",
	"Campfire_burning_F",
	"Land_CampingChair_V1_F",
	"Land_CampingTable_F"
];
